### ISSUE TITLE
Printing of Inf

### ISSUE THREAD

**Issue by mlubin** [quinnj/JSON3.jl#101]
This snippet shows the current behavior for Inf values:

https://github.com/quinnj/JSON3.jl/blob/a7426d57f693afdf11ded1dd2b47ff91f0c3b7e7/test/json.jl#L32-L43

While unfortunately JSON doesn't define how to serialize Inf and NaN, it seems like the most common workaround is to use the Javascript names `Infinity` and `NaN`; see, e.g., Python's built-in JSON library: https://docs.python.org/3/library/json.html#infinite-and-nan-number-values. Printing `Inf` as `Infinity` would make JSON3 more interoperable.

**Comment by quinnj** [comment]
Yeah, I'm happy to change the printing here; on the reading side, we actually already support reading `Infinity`, so it's just writing that would change. Care to make a PR?
