### ISSUE TITLE
Reading issue with named tuples

### ISSUE THREAD

**Issue by encendre** [quinnj/JSON3.jl#110]
Hi, first of all thank you for this package which I find very practical.

I have some problems with reading named tuples
Let's take this code as an example

```julia
mutable struct Bar
  data::Int
  
  Bar() = new()
end

StructTypes.StructType(::Type{Bar}) = StructTypes.Mutable()

data = """{
  "bar": {
    "data": 1
  }
}"""

JSON3.read(data, @NamedTuple begin
  bar::Bar
end)
```

It produces the following error:
```
MethodError: Cannot `convert` an object of type Dict{String,Any} to an object of type Main.workspace174.Bar
```

The example may seem irrelevant, but in my use case, i use parametric and abstract type and I found more pleasant to use to use a named tuple as parameter instead of declaring a new structure for each kind of message.
Currently my definition of subtypes looks something like this:

```julia
StructTypes.StructType(::Type{Message}) = StructTypes.AbstractType()
StructTypes.StructType(::Type{<:Message}) = StructTypes.Mutable()
StructTypes.subtypekey(::Type{Message}) = :method
StructTypes.subtypes(::Type{Message}) = (
  getfoos = Message{@NamedTuple begin
    some_information::String
    foos::Array{Foo}
  end},
  # ...
)
```
Is there a better way to do this, or a way to fix the error?

**Comment by quinnj** [comment]
This should be fixed in #113
