### ISSUE TITLE
Microsecond parsing

### ISSUE THREAD

**Issue by Quafadas** [quinnj/JSON3.jl#114]
```
testDate ="""["2020-12-07T21:03:37.329261"]"""
JSON3.read(testDate, Array{DateTime}, dateformat=DateFormat("yyyy-mm-ddTHH:MM:SS.ssssss"))
```

Any ideas on how to manage this? The timeformat is coming at me from a third party API, accessed over HTTP, so there isn't an obvious may for me to manipulate these strings before they hit JSON3. Is this related to no microsecond constructor in Julia core DateTime support?

**Comment by quinnj** [comment]
There's nothing in JSON3 we can do about supporting microseconds w/ DateTime; you could potentially try making your own wrapper type that supported more precision though. Something like:
```julia
struct DateTime2
    datetime::DateTime # handles year/month/day/hour/minute/second
    time::Time # handles any subsecond
end

StructTypes.StructType(::Type{DateTime2}) = StructTypes.StringType()

function DateTime2(input::String)
    dt, tm = split(input, '.')
    time = Time(Nanosecond(Microsecond(parse(Int, tm))))
    return DateTime2(DateTime(dt), time)
end

function Base.show(io::IO, dt::DateTime2)
    print(io, dt.datetime)
    print(io, '.')
    print(io, string(dt.time)[10:end])
end
```

Which allows doing the following for your original example:

```julia
julia> JSON3.read(testDate, Array{DateTime2})
1-element Vector{DateTime2}:
 2020-12-07T21:03:37.329261
```

**Comment by robertdj** [comment]
I have a similar situation, but I want to read into a larger struct, e.g.

``` julia
struct Foo
    A::Int
    B::Dates.DateTime
end

StructTypes.StructType(::Type{Foo}) = StructTypes.Struct()
```

With only milliseconds it works:

``` julia
test_data1 = """{"A":1, "B":"2020-12-07T21:03:37.329"}"""
JSON3.read(test_data1, Foo)
```

I don't need precision below milliseconds, so I just have a function that discards those digits:

``` julia
function truncate_milliseconds(t::String)
    dt, ms = split(t, '.')
    Dates.DateTime(dt * "." * ms[1:3])
end
```

I make a constructor that converts the strings to `DateTime`s:

``` julia
function Foo(A, B::String)
    Foo(A, truncate_milliseconds(B))
end
```

However, it doesn't work. It appears that it doesn't invoke the appropriate constructor

``` julia
test_data2 = """{"A":1, "B":"2020-12-07T21:03:37.329261"}"""
JSON3.read(test_data2, Foo)
```

Do you know how to handle this case?
