### ISSUE TITLE
Function for writing JSON to a file

### ISSUE THREAD

**Issue by yurivish** [quinnj/JSON3.jl#115]
Writing JSON files is a common use case for this package, but right now `JSON3.write(fname, contents)` fails. In contrast, base Julia implements `write(fname, contents)` and the `CSV` package implements `CSV.write(fname, contents)`.

It looks like adding the following to `write.jl` suffices to implement `JSON3.write(fname, contents)`:

```
function write(fname::String, obj::T; kw...) where {T}
    open(fname, "w") do io
        write(io, obj; kw...)
    end
    fname
end
```

Would there be interest in adding this functionality to JSON3?

**Comment by quinnj** [comment]
Yeah, I'd be ok adding that convenience definition.
