### ISSUE TITLE
JSON3.read(::AbstractCmd) ?

### ISSUE THREAD

**Issue by oxinabox** [quinnj/JSON3.jl#127]
There are some commandline tools that output JSON to std-out.
Right now to use JSON3 with them is pretty easy:
```julia
data = JSON3.read(read(`foobar`))
```
but it would be slightly cleaner if `read` accepted an `AbstractCommand` like `Base.read` does.

then it would be just

```julia
data = JSON3.read(`foobar`)
```

**Comment by quinnj** [comment]
Yeah, that sounds fine to me; care to make a PR?

**Comment by oxinabox** [comment]
Sure
