### ISSUE TITLE
Read JSON with missing fields

### ISSUE THREAD

**Issue by f-L0x** [quinnj/JSON3.jl#134]
Hi

I would like to read a json with some "missing" fields
"Missing" here realy means the field is not there

Example:
```julia
using JSON3
using StructTypes

json_full_info = """[{ "name":"Jane", "age":19 },{ "name":"John", "age":25 }]"""
json_null_info = """[{ "name":"Jane", "age":19 },{ "name":"John", "age":null }]"""
json_miss_info = """[{ "name":"Jane", "age":19 },{ "name":"John"}]"""

mutable struct Person
    name::String
    age::Union{Int64,Nothing}
end
StructTypes.StructType(::Type{Person}) = StructTypes.Struct()

persons_full = JSON3.read(json_full_info, Vector{Person})
persons_null = JSON3.read(json_null_info, Vector{Person})
persons_miss = JSON3.read(json_miss_info, Vector{Person})
```

`persons_full ` and `persons_null ` works fine
But `persons_miss ` creates an error because "age:" is missing

Is there a elegant way to solve this?

Thanks

**Comment by quinnj** [comment]
Yes, you should use the [`StructTypes.Mutable()`](https://juliadata.github.io/StructTypes.jl/stable/#StructTypes.Mutable) definition instead. So something like:
```julia
mutable struct Person
    name::String
    age::Union{Int64,Nothing}
end
Person() = Person("", nothing) # empty constructor required by StructTypes.Mutable()

StructTypes.StructType(::Type{Person}) = StructTypes.Mutable()
```

**Comment by f-L0x** [comment]
Thank you very much.
Maybe it makes sense to put an example with StructTypes.Mutable() in the documentation.
At least I have overseen it or didn't read careful enough.
