### ISSUE TITLE
Reading floating point numbers into nonstandard type

### ISSUE THREAD

**Issue by jmkuhn** [quinnj/JSON3.jl#135]
```
julia> using DecFP, JSON3

julia> JSON3.read("0.1", Dec128)
0.1000000000000000055511151231257827
```
The value is going through `Float64` before being converted to a `Dec128`.

I have been able to work around this using `JSON3.RawType()`.

**Comment by quinnj** [comment]
Yeah, `RawType` sounds like the right approach here. Is there something you think JSON3.jl should change here?

**Comment by jmkuhn** [comment]
I was surprised that it wasn't doing a `parse(Dec128, "0.1")` but I am satisfied with `RawType`.
