### ISSUE TITLE
DateTime usage

### ISSUE THREAD

**Issue by lsaenzt** [quinnj/JSON3.jl#163]
Hi,
I am trying to use the new datetime feature together with float parsing (both great additions).  I am having trouble to make it work. 

This is an example:

```    
using Dates, JSON3, StructTypes

json = """{"price":"15.345","time":"2020-02-21T21:58:00.000000000Z"}"""

mutable struct price
    price::Float64
    time::DateTime

     price() = new()
end

StructTypes.StructType(::Type{price}) = StructTypes.Mutable()

df=dateformat"yyyy-mm-ddTHH:MM:SS.sssssssssZ"

JSON3.read(json,price;datetime=df,parsequoted=true)

```

The datetime format works correctly.

````
DateTime("2020-02-21T21:58:00.000000000Z",df)
``

Am I using the datetime keyword correctly?

Thanks in advance.

**Comment by quinnj** [comment]
The keyword argument you want is `dateformat=df`

**Comment by lsaenzt** [comment]
Thank you. I don`t know what I was thinking when I wrote that code... It's embarrasing. 
Sorry for wasting your time.

Works perfect.
