### ISSUE TITLE
Nested tab complete

### ISSUE THREAD

**Issue by anandijain** [quinnj/JSON3.jl#177]
Maybe this is just me, but accessing nested structure in the REPL will have tab completion for the top level, but any nested structure doesn't work.

Is this possible given the type hierarchy? It's a little annoying to have to define intermediate variables for each level of nesting. 
```julia
x = json.field
x2 = x.field2
x3 = x2.field3
```
close if you feel like it

**Comment by quinnj** [comment]
There isn't anything (I think) we can do in JSON3.jl for this, since htis is a REPL.jl stdlib Julia issue; see the discussion here: https://github.com/JuliaLang/julia/issues/36437
