### ISSUE TITLE
Parsing mutable structs is faster than immutable

### ISSUE THREAD

**Issue by mmiller-max** [quinnj/JSON3.jl#181]
I expected immutable structs to be faster for the example below, but it seems they are not. Can this be improved?

```
struct S1
    val::String
end
StructTypes.StructType(::Type{S1}) = StructTypes.Struct()

mutable struct S2
    val::String
    S2() = new()
end
StructTypes.StructType(::Type{S2}) = StructTypes.Mutable()

str = "{\"val\": \"name\"}"
@btime JSON3.read($str, $S1) # 192.807 ns (2 allocations: 368 bytes)
@btime JSON3.read($str, $S2) # 150.040 ns (2 allocations: 48 bytes)
```

Is it because in the case of `Struct` it builds the `Vector{Any}`?

**Comment by quinnj** [comment]
You can use `StructTypes.UnorderedStruct()`, which should be much faster (but requires the fields to be provided in the correct order in JSON; if it's just a single field, it shouldnt' matter)

**Comment by mmiller-max** [comment]
I think you meant `StructTypes.OrderedStruct()` but yep this is much quicker.

```Julia
julia> StructTypes.StructType(::Type{S1}) = StructTypes.OrderedStruct()

julia> @btime JSON3.read($str, $S1) # 192.807 ns (2 allocations: 368 bytes)
  56.995 ns (1 allocation: 32 bytes)
```

I think I can make a lot of use of ordered structs actually. Awesome.

Out of interest for my original question, is it expected that `Struct` is slower than `Mutable` or does it really depend on the case?

**Comment by quinnj** [comment]
Yep sorry, `OrderedStruct` should be faster. I would say it depends on the case; # of fields + types of fields will all affect the various struct vs. mutable performance.
