### ISSUE TITLE
option to read into `AbstractDict{String,<:Any}`

### ISSUE THREAD

**Issue by ExpandingMan** [quinnj/JSON3.jl#182]
I don't know whether to think this is a huge feature request, or a tiny one, considering that there is already so much machinery to parse things into arbitrary data structures.

Anyway, I don't mind the choice of `Symbol` as key, but it can be inconsistent with conventions that a lot of other things take.  In particular, JSON.jl, TOML.jl, LightBSON.jl all parse into structures with strings as keys.  In some cases, it would be make life simpler if JSON3.jl can do this as well.  I'm currently writing a package that uses both this and LightBSON.jl and as far as I know, I can't make the outputs consistent without a ton of extra allocations.

**Comment by quinnj** [comment]
I'm not sure I quite understand the request here; `JSON3.Object` uses `Symbol` since it also allows using them as "properties" via `getproperty`. Is there a reason you can't just do `obj = JSON3.read(json, Dict{String, Any})`?

**Comment by ExpandingMan** [comment]
That forces you to allocate the whole thing instead of reading it lazily though, right?

**Comment by ExpandingMan** [comment]
Ok, I apparently just have no clue how this works
```
◖◗ @btime JSON3.read(str);
  2.144 ms (30 allocations: 982.92 KiB)

◖◗ @btime JSON3.read(str, Dict{String,Any});
  1.111 ms (29958 allocations: 1.12 MiB)
```
In the former case it returns a `JSON3.Object` which I figured was essentially a view while in the latter case it allocates a new dict.  Maybe it's just such an expensive view that it doesn't matter except in extreme cases.

Regardless, I should have taken the time to know what the hell I was talking about before opening this issue!  Doesn't look like there's anything to be done here, thanks!
