### ISSUE TITLE
Issues when generating types for ENSEMBL JSON

### ISSUE THREAD

**Issue by alyst** [quinnj/JSON3.jl#197]
I'm trying to use JSON3 for processing [ENSEMBL](https://ensembl.org) JSON files (e.g. [this one](http://ftp.ensembl.org/pub/current_json/homo_sapiens/homo_sapiens.json)).
The original file is 4GB, I've attached the small excerpt ([ensembl_homo_sapiens_20210521_small.json.gz](https://github.com/quinnj/JSON3.jl/files/7747048/ensembl_homo_sapiens_20210521_small.json.gz)).

I have a few issues when trying to generate types:
```julia
ensembl_json_str = String(read("ensembl_homo_sapiens_20210521_small.json"));
using JSON3
JSON3.writetypes(ensembl_json_str, "json_types.jl")
```

The first error is array access in `collapse_unions!()` function. That's because when checking for the nested union it only looks whether the argument is subexpression and doesn't check if it's `Union` (in that case it is `Vector{T} where T` and `u.args` have just 2 arguments, so `u.args[2:3]` throws). I fix it by changing [this line](https://github.com/quinnj/JSON3.jl/blob/main/src/gentypes.jl#L150) into
```julia
        if isa(expr.args[end], Expr) && (expr.args[end].args[1] == :Union) # nested union
``` 

But then there are a few issues in the resulting `json_types.jl`:
```julia
mutable struct Xref
    display_id::String
    primary_id::String
    db_display::Union{Nothing, String}
    info_type::Union{Nothing, String}
    info_text::Union{Nothing, String}
    dbname::String
    description::Union{Nothing, String}
    linkage_types::Union{Nothing, Vector{T} where T}
    associated_xrefs::Union{Nothing, Vector{Any}}
    Xref() = new()
end
```
It looks like there is no type generated for `linkage_types` elements (and the initial error with `collapse_unions!()` seems also to be related to `linkage_types`).

Then there are types like:
```julia
mutable struct Exon
    seq_region_name::String
    strand::String
    id::String
    end::String
    start::String
    Exon() = new()
end
```
which is clearly a syntax error, because `end` is Julia keyword.

**Comment by mcmcgrath13** [comment]
Thanks! I'll look into the union issue you raised.

The reserved words as fieldnames is an interesting problem.  What would you like/expect to see in that case?  Error/warn? We could generate a random variable name and append it? Put an underscore in front of it? Given that the type would then need to be used by JSON3/StructTypes a `names` method would likely needed to be added as well if the variable was mapped to a new name.

**Comment by alyst** [comment]
> I'll look into the union issue you raised.

Thank you!

> What would you like/expect to see in that case? Error/warn?

I think such JSONs are perfectly fine from JSON format PoV, so *JSON3.jl* should support them.
I'm very new to *JSON3*, so I don't know if it supports custom mapping of *JSON* identfiers to field names already. It would be nice if JSON3-generated types provide some default mapping, which could be adjusted by the user.
Underscores before/after looks like the most straightforward solution (except that it would require implementing the logic to deal with JSON files that contain "end_" fields or even both "end_" and "end" fields).

**Comment by mcmcgrath13** [comment]
Yes, the `StructTypes.names` method can be overloaded to provide that mapping, so it's a question of figuring out what an autogenerated field name to target for that ought to be.  The generated random variable appended to the original keyword json name is the least likely to run into clashes, which is a pro.  It's pretty ugly, which is a con.  But the user could always edit it to a different valuable post writing to file, so I think the ugliness is not a major con.

**Comment by alyst** [comment]
> Yes, the StructTypes.names method can be overloaded to provide that mapping

Ah, that's great! So in the situations like with `struct Exon` it would be nice if the generated types code provides the `names()` implementation.

>  The generated random variable appended to the original keyword json name is the least likely to run into clashes, which is a pro.

Even if it would be a random variable, I think *JSON3* should implement a duplicate field names check. So it could also be less random, e.g. `end1`, `end2` etc.
Actually, I think the logic here would be very similar to what is implemented in *DataFrames.jl* for checking and enforcing the uniqueness of column names (and I think they also check if the column name clashes with the Julia keywords).

**Comment by alyst** [comment]
Some updates to the issue: actually, I have observed that *JSON3.jl* already uses `@var_str` for JSON identifiers that contains characters that are illegal for Julia identifiers.
`@var_str` will also work for identifiers that are Julia keywords (like `var"end"`). I've manually updated the generated types to check that. So `var"end"` looks like the most straightforward solution.

There are however, other issues with the generated types for this sample Ensembl JSON:
  * `mutable struct GO` is duplicated (with slight differences in the declared fields). It's used in JSON in 2 different places, but in this case it makes sense to use the same structure. (In other cases it might be required to generate types with different names).
  * `linkageTypes` and `translocations` fields have type `Vector{T} where T`, and the underlying types (`LinkageType`, `Source` and `Translocation`) are not generated

**Comment by mcmcgrath13** [comment]
I've made some progress on the issues raised here:

#199 should automatically add the `var"end"` (or other reserved keyword) to the written types.
#200 should fix the collapsing of unions as well as the generation of `LinkageType` and `Translocation`

Once those are merged in, I'll tackle the duplicate structs.  @alyst if you could take a look at the code/verify it's working for you, that would be great!
