### ISSUE TITLE
using `print` with `JSON3.pretty` appends a `nothing` at the end 

### ISSUE THREAD

**Issue by kdheepak** [quinnj/JSON3.jl#204]
Hi, thanks for making this package. This is my first time using it, so feel free to close this issue if you think there's a good reason for this behavior. 

Currently, using `print` or `println` results in a `nothing` added to the end.

```julia
julia> println(JSON3.pretty(["hello", "world"]))
[
  "hello",
  "world"
]nothing
```

Is this expected behavior?

**Comment by mcmcgrath13** [comment]
I’m on my phone, so haven’t double checked this. But I’m pretty sure pretty
prints then returns nothing. So println is only seeing the returned nothing
and printing that.

**Comment by kdheepak** [comment]
I’m in a Julia REPL and when an expression returns nothing, the Julia REPL doesn’t display it. I’ll share a screenshot when I’m back at my computer.

**Comment by mcmcgrath13** [comment]
Julia doesn't display nothing when returned, but it will print it when expressly asked.

```
julia> println(nothing)
nothing
```

**Comment by kdheepak** [comment]
Oh my. I understand what I was doing incorrectly. `JSON3.pretty(expr)` pretty prints `expr` to stdout, and the return value of `JSON3.pretty(expr)` is `nothing` which is what I was printing to the terminal. Oof.
