### ISSUE TITLE
Get from https url in company network with self signed certificate

### ISSUE THREAD

**Issue by chunjiw** [quinnj/JSON3.jl#237]
When I do `HTTP.get("https://www.google.com")` using company network, I get a long error message beginning with `MbedTLS error code -9984: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed`.

I know that the company network has a self signed certificate in the certificate chain which might be the culprit.

However, the thunder REST client plugin in VS Code has no problem getting a 200 response from `https://...`

I don't know how to debug this. Is there something we can do in HTTP.jl to address this? What other information do I need to provide?

**Comment by mcmcgrath13** [comment]
Did you mean to open this issue in [HTTP.jl](https://github.com/JuliaWeb/HTTP.jl)? This issue seems unrelated to JSON

**Comment by chunjiw** [comment]
Oops.... My bad. Thank you for pointing it out!
