### ISSUE TITLE
JSON3.read files directly 

### ISSUE THREAD

**Issue by onetonfoot** [quinnj/JSON3.jl#241]
Would you consider supporting reading files directly as I think it could make the API more intuitive. For example, I often find myself writing.

```julia
JSON3.read("file.json", Dict)
```

After getting an error I correct it to

```julia
JSON3.read(read("file.json"), Dict)
```

However, I think I'm used to the first example from other packages e.g

```julia
df = CSV.read("data.csv", DataFrame)
s = read("file.txt", String)
```

Anyways thank for you your work so far!

**Comment by quinnj** [comment]
Yeah, I wonder if we just did `isfile(json) ? Mmap.mmap(json) : json` if that would work for people.

**Comment by onetonfoot** [comment]
Yeahh I think that would suffice

**Comment by mcmcgrath13** [comment]
You might also need to do a check on the json length before the `isfile` check.  I vaguely remember a footgun here and the implementation of [`json_read_str` in gentypes.jl](https://github.com/quinnj/JSON3.jl/blob/765c3bf7eb4a392cf94d4852fdaf6df363526ed2/src/gentypes.jl#L441) does that check probably for good reasons. (or maybe obsolete reasons 🤷)

**Comment by onetonfoot** [comment]
Thanks yeah it's still relevant because `isfile` will throw [an error](https://github.com/JuliaLang/julia/issues/39774) with a string longer than that than 255. 

https://github.com/quinnj/JSON3.jl/pull/243

**Comment by onetonfoot** [comment]
https://github.com/quinnj/JSON3.jl/pull/243
