### ISSUE TITLE
new patch version ?

### ISSUE THREAD

**Issue by rafaqz** [quinnj/JSON3.jl#259]
I'm getting this error in CI using GeoJSON.jl:

`ArgumentError: invalid JSON at byte position 1 while parsing type GeoJSON.GeoJSONT{3, Float32}: ExpectedOpeningObjectChar`

https://github.com/asinghvi17/GeometryOps.jl/actions/runs/5103788535/jobs/9175150060#step:7:281

The good news is it works on master, we just need a patch version :)

**Comment by quinnj** [comment]
1.13 is now released
