### ISSUE TITLE
Confused with the nested `JSON3.construct`

### ISSUE THREAD

**Issue by findmyway** [quinnj/JSON3.jl#26]
```julia
julia> using JSON3

julia> struct A
             b::Int
             c::Int
             end

julia> struct B
              a::A
              b::Int
              end

julia> JSON3.StructType(::Type{B}) = JSON3.ObjectType()

julia> JSON3.StructType(::Type{A}) = JSON3.ObjectType()

julia> JSON3.construct(::Type{B}, x::Dict) = B(JSON3.construct(A, x[:a]), x[:b])

julia> JSON3.construct(::Type{A}, x::Dict) = A(x[:b], x[:c])

julia> JSON3.read("""
              {
                  "b":1,
                  "a": {"b":5, "c":8 }
              }""", B)
ERROR: KeyError: key :b not found
......
```

But if I define the constructor of A like this:
```julia
julia> JSON3.construct(::Type{A}, x::Dict) = A(x["b"], x["c"])

julia> JSON3.read("""
              {
                  "b":1,
                  "a": {"b":5, "c":8 }
              }""", B)
B(A(5, 8), 1)
```
It works fine. However, the following will not work now:
```julia
julia> JSON3.read("""
       {
           "b":1,
           "c":2
       }""", A)
ERROR: KeyError: key "b" not found
Stacktrace:
......
```

Any suggestions for how to deserialize nested struct?

**Comment by quinnj** [comment]
@findmyway, sorry for the slow response. This works if you do:
```julia
JSON3.construct(::Type{B}, x::Dict) = B(A(x[:a]["b"], x[:a]["c"]), x[:b])
```

This is because the default object type is `Dict{Symbol, Any}`, which is why in your `JSON3.construct` method, you refer to `x[:a]` and `x[:b]`; but because of the `Any` in `Dict{Symbol, Any}`, when we parse `{"b":5, "c": 8}`, we, by default, parse an untyped object as `Dict{String, Any}`.

**Comment by findmyway** [comment]
Now I see, thanks! 

But I think this inconsistent behavior will double the work to define the constructor.

> when we parse {"b":5, "c": 8}, we, by default, parse an untyped object as Dict{String, Any}

I think this should appear in the doc. Is there any special reason to not use `Dict{Symbol, Any}` here?
