### ISSUE TITLE
Why `JSON3.read` is used both for file path and json string content, and blocks file after read?

### ISSUE THREAD

**Issue by sairus7** [quinnj/JSON3.jl#272]
Because of this I get read error for any non-existent file, and maybe some incorrect behaviour for file names that match JSON 
```julia
using JSON3
JSON3.read("123") # is it file or value? now its a value
open("123", "w") do io
    write(io, """
    {
        "some":"data"
    }
    """)
end
JSON3.read("123") # but now this is file
rm("123") # unlink("123"): permission denied (EACCES)
```

**Comment by 0x0f0f0f** [comment]
See how this is done for [TOML for example](https://github.com/JuliaLang/TOML.jl/blob/master/src/TOML.jl). It's either `parsefile`, `tryparsefile` or `parse` and `tryparse`. The decision of whether it's a file path or a TOML string is done by the caller!

**Comment by 0x0f0f0f** [comment]
Same for YAML: https://github.com/JuliaData/YAML.jl/blob/master/src/YAML.jl

**Comment by 0x0f0f0f** [comment]
Cross ref https://github.com/quinnj/JSON3.jl/issues/95 

The solutions could be many:
- Make two different functions, `read_file` and `read`. One reads a file and the other reads a string with the contents of the files, as TOML and YAML already do. Disallow reading from a file in `read`.
- Add a kwarg, `readfile=false`. Backwards compatible but not really the nicest.
- Leave `read` functionality as-is and add `read_file` and `read_string`.

**Comment by 0x0f0f0f** [comment]
I'm happy to file a PR once we agree on a solution

**Comment by JeffBezanson** [comment]
:+1:  I agree file/string should be separate functions. An additional problem with this API is that when you do trimming, all the code for Mmap/files has to be included even if you aren't using files.

**Comment by JeffBezanson** [comment]
I think we should add `parse` and `parsefile`, since JSON3 doesn't yet use those names so it would be backwards compatible, and similar to what other packages do.
