### ISSUE TITLE
Support Tuple-type parsing for individual elements

### ISSUE THREAD

**Issue by JeffreySarnoff** [quinnj/JSON3.jl#28]
Reading a JSON encoded `Symbol` (which encodes as a string) requires `Meta.parse` rather than `parse`.

this is from see https://discourse.julialang.org/t/how-to-read-tuples-with-json3/29843

**Comment by quinnj** [comment]
This isn't a Symbol issue, but a Tuple issue.

**Comment by quinnj** [comment]
Implemented in https://github.com/quinnj/JSON3.jl/pull/29
