### ISSUE TITLE
A proper documentation workflow, with 'stable/latest' links from readme

### ISSUE THREAD

**Issue by tanhevg** [quinnj/JSON3.jl#48]
Currently, `README.md` in master has already been updated to refer to `StructTypes` as a separate package. Meanwhile, in the latest tagged release of JSON3 the new package has not yet been factored out. This is causing confusion.

The solution would be to  have a very brief generic description in `README.md`, and have proper documentation built by `Documenter` (or any other preferred solution), which would follow the usual 'latest/stable' contract, and put the links to both versions on the README.

**Comment by quinnj** [comment]
Fixed via fad6527c3a9f30e4815adac15a9f33d2d754ea95
