### ISSUE TITLE
Define JSON3.StructTypes for all the standard libraries

### ISSUE THREAD

**Issue by yakir12** [quinnj/JSON3.jl#5]
Maybe there is a way to automate this? 

For example:
```julia
using JSON3, Dates
JSON3.write(now())
```

**Comment by quinnj** [comment]
Yeah, now that we don't have an automatic fallback for any type, we need to open issues for things that don't have a defined `StructType` and figure out what the appropriate definition would be. For Date/DateTime/Time, I think it makes sense to define them as `JSON3.StringType`.

**Comment by yakir12** [comment]
Currently I'm just doing this:
```julia
for y in (<modules I need to save to JSON>), x in names(y, all = true)
    T = getproperty(y, x)
    if T isa DataType # a "normal" type
        JSON3.StructType(::Type{T}) = JSON3.Struct()
    elseif T isa UnionAll # a parametric type
        JSON3.StructType(::Type{<:T}) = JSON3.Struct()
    end
end
```
Before I start opening issues on every single undefined "standard" type, is there any rigorous way you want to go about this...? Like should we open an issue, discuss what the best way is, and PR following that discussion? I guess the first thing would be to compile a list of ALL the types JSON3 would be expected to deal with. This alone might be daunting, consider:
```julia
using JSON3, Dates
x = now()
JSON3.StructType(::Type{DateTime}) = JSON3.Struct()
txt = JSON3.write(x)
```
errors cause 
```julia
Dates.UTInstant{Millisecond} doesn't have a defined `JSON3.StructType`
```
`UTInstant` isn't even exported from `Dates`. So it's not totally obvious what should be included or not....

**Comment by quinnj** [comment]
Implemented in https://github.com/quinnj/JSON3.jl/pull/30
