### ISSUE TITLE
Pretty printing

### ISSUE THREAD

**Issue by tanhevg** [quinnj/JSON3.jl#52]
Thanks for the lovely package!

One feature that I miss from `JSON2.jl` is pretty printing. One quick way of providing this would be just lifting `pretty.jl` from there into this package. Ideally it would probably be neater from the users' point of view to have a keyword argument in `write(..., pretty=true)`, such that we don't need to blow up the string in memory for large structs.

**Comment by EricForgy** [comment]
To do this, we'll need to port over

https://github.com/quinnj/JSON2.jl/blob/master/src/pretty.jl

(note to self) :)

**Comment by quinnj** [comment]
Implemented in https://github.com/quinnj/JSON3.jl/pull/67
