### ISSUE TITLE
Less verbose pretty()

### ISSUE THREAD

**Issue by lbilli** [quinnj/JSON3.jl#68]
Great addition the new pretty printing feature! :+1:

Is is possible to mute the `str = "..."` messages? 
It looks like they have mainly a debugging purpose.
```julia
julia> JSON3.pretty(JSON3.write([1,2]))
str = "[1,2]"
[
  str = "1"
1,
  str = "2"
2
]
```

**Comment by quinnj** [comment]
Oops! How embarrassing! Fixed in https://github.com/quinnj/JSON3.jl/commit/bda1550f4e4d5e7644388ac71584c28307e2afa6
