### ISSUE TITLE
Trouble reading in a file

### ISSUE THREAD

**Issue by bkamins** [quinnj/JSON3.jl#75]
This file https://raw.githubusercontent.com/jeffreylancaster/game-of-thrones/master/episode-character/episode-character.json does not load correctly with an error:
```
ERROR: ArgumentError: invalid JSON at byte position 1 while parsing type Any: InvalidChar
```
while JSON.jl reads it in without a problem.

**Comment by quinnj** [comment]
You need to pass a byte buffer or json string literal as the argument to `JSON3.read`, not a file name. To read a file, you can do `JSON3.read(read(filename))`

**Comment by bkamins** [comment]
Thank you! Right - sorry for mixing up things. A think to consider is making things more consistent across CSV.jl and JSON3.jl (as I just reused the pattern I expected to work without reading the documentation).
