### ISSUE TITLE
Issue with Array eltype promotions

### ISSUE THREAD

**Issue by lbilli** [quinnj/JSON3.jl#8]
When parsing arrays, the eltype looks correct here:
```julia
JSON3.read("[1.2, 2.0]")
2-element JSON3.Array{Union{Float64, Int64}, ...
```
but not here:
```julia
JSON3.read("[1.2, 2.0, 3.3]")
3-element JSON3.Array{Any, ...
```
I would have expected `Union{Float64, Int64}`, or even better, just `Float64` in both cases.

**Comment by quinnj** [comment]
Thanks for opening an issue! I included a few tweaks to help in https://github.com/quinnj/JSON3.jl/pull/10. I fixed the promotion from `Union{Int, Float64}` to `Any`, and also changed so if you've parsed a `Float64`, then it will only try to parse `Float64` for the rest of the array. The one case where you'll still get `Union{Int, Float64}` is a case like `JSON3.read("[1.0, 2.1]")`, which may not be ideal, but I'm not sure quite how we could handle that without just parsing `Float64` for every number.

**Comment by quinnj** [comment]
Merged #10

**Comment by lbilli** [comment]
Thanks for the quick fix!

However, I still find some odd behavior:
```julia
JSON3.read("[1.2, null, 3.3]")
3-element JSON3.Array{Union{Nothing, Float64}, ... # ok

JSON3.read("[1.2, null, 3.0]")
3-element JSON3.Array{Any, ...                     # I was hoping for the same as above 
```
My use case is a numeric array that may contain missing values, encoded as `null`. It'd be useful to know whether there are any `null` without scanning the array, since the parser already has this information.

It already works as expected for `Int64` or `String`.

**Comment by lbilli** [comment]
Thanks again for taking care of this so promptly.

I'm sorry to keep dragging this on, but I'd like to mention that the last remaining case that is still less then ideal is when the first non-`null` element in a `Float` array happens be an `Int`, in which case the eltype depends on the order of the elements:
```julia
JSON3.read("[1.2, 3, null]")    # Union{Nothing, Float64}

JSON3.read("[3, 1.2, null]")    # Union{Nothing, Float64, Int64}

JSON3.read("[3, null, 1.2]")    # Any

JSON3.read("[null, 3, 1.2]")    # Any

JSON3.read("[null, 1.2, 3]")    # Union{Nothing, Float64}

```

**Comment by quinnj** [comment]
Sorry for being slow here, here's some more improvements: https://github.com/quinnj/JSON3.jl/pull/16
