### ISSUE TITLE
Relaxed JSON

### ISSUE THREAD

**Issue by jdonnerstag** [quinnj/JSON3.jl#84]
thanks a lot for this great package. 

We have plenty json config files, which are maintained by people. Does JSON3 support some sort of relaxed JSON syntax, e.g. 

- support comments, such as '#' or '//' 
- { a: 1 } instead of {"a": 1 }
- { a: 1, } ignore extra comma
- {
    a: 1
    b: 2,
    c: 3
  }   ',' may be skipped in multi-line constructs outside multi-line string "..\r\n..". Yet ',' may optionally still be used.
- may be even: optional { } on root level

If not supported yet, would it be complicated to add this feature? May be via read_relaxed(..) or similar.

**Comment by quinnj** [comment]
This would be pretty complicated to add; the JSON spec is pretty strict, so it's unusual for something to claim itself as "json" but not adhere to the pretty-well-documented specification. Perhaps your files are actually YAML? YAML is an extremely flexible config format where valid JSON is actually valid YAML. What you're describing sounds like it would be valid YAML, so I would maybe try parsing your files with https://github.com/JuliaData/YAML.jl
