### ISSUE TITLE
Add support for parsing one object per line

### ISSUE THREAD

**Issue by sa-** [quinnj/JSON3.jl#86]
Right now there is no option to read a file that is structured like this.
```
{"a": 1}
{"a": 3}
```

BigQuery and Apache Spark output their json in this format.

Pandas has a neat feature `pd.read_json(..., lines=True)`, which allows it to parse files that are structured like this.

This speedbump has prevented me from reading a JSON file into a DataFrame for a few days now. 

PS: I'm open to contributing if I could get some pointers on where to start

**Comment by DilumAluthge** [comment]
Does this package provide the functionality you need?

https://github.com/danielw2904/JSONLines.jl

**Comment by DilumAluthge** [comment]
Alternatively, you could iterate over the file using `eachline` and pass each line to JSON3.jl.

**Comment by quinnj** [comment]
This functionality was added in the most recent 1.5 release; you can now do `JSON3.read(json; jsonlines=true)`. PR ref: https://github.com/quinnj/JSON3.jl/pull/99
