### ISSUE TITLE
Converting `JSON3.Object` and `JSON3.Array` to `Dict` and `Vector`, respectively

### ISSUE THREAD

**Issue by DilumAluthge** [quinnj/JSON3.jl#98]
Suppose that I have a `JSON3.Object` or a `JSON3.Array`. I'd like to now to convert it to a Base `Dict` or a Base `Vector`, respectively.

And I'd like to do so recursively. E.g. if the `JSON3.Object` or `JSON3.Array` contains other `JSON3.Object`s and/or `JSON3.Array`s, I'd like to also convert all of those to `Dict`s and `Vector`s, respectively.

What is the easiest way to do this?

**Comment by quinnj** [comment]
Just call `copy(x)`; it should also work recursively. (sorry for the slow response!)

**Comment by DilumAluthge** [comment]
That works perfectly! Should we add this to the documentation somewhere?
